//! Maps file extensions to tree-sitter grammars.

use std::path::Path;

use tree_sitter::Language;

/// A supported source language.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Lang {
    Bash,
    C,
    CMake,
    CSharp,
    Cpp,
    Css,
    Dart,
    Elixir,
    Elm,
    Erlang,
    FSharp,
    FSharpSignature,
    Gleam,
    Go,
    Haskell,
    Hcl,
    Html,
    Java,
    JavaScript,
    Julia,
    Kotlin,
    Lua,
    Nix,
    ObjC,
    OCaml,
    OCamlInterface,
    Php,
    Python,
    R,
    Ruby,
    Rust,
    Scala,
    Swift,
    Toml,
    TypeScript,
    Tsx,
    Yaml,
    Zig,
}

impl Lang {
    /// Picks a language from the file name, or `None` when the tool does not
    /// know how to parse the file.
    pub fn from_path(path: &Path) -> Option<Lang> {
        let name = path.file_name()?.to_str()?;
        match name {
            "Dockerfile" | "Makefile" => return None,
            "CMakeLists.txt" => return Some(Lang::CMake),
            ".bashrc" | ".bash_profile" | ".zshrc" | ".profile" => return Some(Lang::Bash),
            "Rakefile" | "Gemfile" | "Vagrantfile" => return Some(Lang::Ruby),
            _ => {}
        }
        let ext = path.extension()?.to_str()?;
        let lang = match ext {
            "sh" | "bash" | "zsh" => Lang::Bash,
            "c" | "h" => Lang::C,
            "cmake" => Lang::CMake,
            "cs" => Lang::CSharp,
            "cc" | "cpp" | "cxx" | "hh" | "hpp" | "hxx" => Lang::Cpp,
            "css" => Lang::Css,
            "dart" => Lang::Dart,
            "ex" | "exs" => Lang::Elixir,
            "elm" => Lang::Elm,
            "erl" | "hrl" => Lang::Erlang,
            "fs" | "fsx" => Lang::FSharp,
            "fsi" => Lang::FSharpSignature,
            "gleam" => Lang::Gleam,
            "go" => Lang::Go,
            "hs" => Lang::Haskell,
            "hcl" | "tf" | "tfvars" => Lang::Hcl,
            "html" | "htm" => Lang::Html,
            "java" => Lang::Java,
            "js" | "mjs" | "cjs" | "jsx" => Lang::JavaScript,
            "jl" => Lang::Julia,
            "kt" | "kts" => Lang::Kotlin,
            "lua" => Lang::Lua,
            "nix" => Lang::Nix,
            "m" => Lang::ObjC,
            "ml" => Lang::OCaml,
            "mli" => Lang::OCamlInterface,
            "php" => Lang::Php,
            "py" | "pyi" => Lang::Python,
            "r" | "R" => Lang::R,
            "rb" | "rake" => Lang::Ruby,
            "rs" => Lang::Rust,
            "scala" | "sc" => Lang::Scala,
            "swift" => Lang::Swift,
            "toml" => Lang::Toml,
            "ts" | "mts" | "cts" => Lang::TypeScript,
            "tsx" => Lang::Tsx,
            "yml" | "yaml" => Lang::Yaml,
            "zig" | "zon" => Lang::Zig,
            _ => return None,
        };
        Some(lang)
    }

    /// Returns the compiled tree-sitter grammar.
    pub fn grammar(self) -> Language {
        match self {
            Lang::Bash => tree_sitter_bash::LANGUAGE.into(),
            Lang::C => tree_sitter_c::LANGUAGE.into(),
            Lang::CMake => tree_sitter_cmake::LANGUAGE.into(),
            Lang::CSharp => tree_sitter_c_sharp::LANGUAGE.into(),
            Lang::Cpp => tree_sitter_cpp::LANGUAGE.into(),
            Lang::Css => tree_sitter_css::LANGUAGE.into(),
            Lang::Dart => tree_sitter_dart::LANGUAGE.into(),
            Lang::Elixir => tree_sitter_elixir::LANGUAGE.into(),
            Lang::Elm => tree_sitter_elm::LANGUAGE.into(),
            Lang::Erlang => tree_sitter_erlang::LANGUAGE.into(),
            Lang::FSharp => tree_sitter_fsharp::LANGUAGE_FSHARP.into(),
            Lang::FSharpSignature => tree_sitter_fsharp::LANGUAGE_SIGNATURE.into(),
            Lang::Gleam => tree_sitter_gleam::LANGUAGE.into(),
            Lang::Go => tree_sitter_go::LANGUAGE.into(),
            Lang::Haskell => tree_sitter_haskell::LANGUAGE.into(),
            Lang::Hcl => tree_sitter_hcl::LANGUAGE.into(),
            Lang::Html => tree_sitter_html::LANGUAGE.into(),
            Lang::Java => tree_sitter_java::LANGUAGE.into(),
            Lang::JavaScript => tree_sitter_javascript::LANGUAGE.into(),
            Lang::Julia => tree_sitter_julia::LANGUAGE.into(),
            Lang::Kotlin => tree_sitter_kotlin_ng::LANGUAGE.into(),
            Lang::Lua => tree_sitter_lua::LANGUAGE.into(),
            Lang::Nix => tree_sitter_nix::LANGUAGE.into(),
            Lang::ObjC => tree_sitter_objc::LANGUAGE.into(),
            Lang::OCaml => tree_sitter_ocaml::LANGUAGE_OCAML.into(),
            Lang::OCamlInterface => tree_sitter_ocaml::LANGUAGE_OCAML_INTERFACE.into(),
            Lang::Php => tree_sitter_php::LANGUAGE_PHP.into(),
            Lang::Python => tree_sitter_python::LANGUAGE.into(),
            Lang::R => tree_sitter_r::LANGUAGE.into(),
            Lang::Ruby => tree_sitter_ruby::LANGUAGE.into(),
            Lang::Rust => tree_sitter_rust::LANGUAGE.into(),
            Lang::Scala => tree_sitter_scala::LANGUAGE.into(),
            Lang::Swift => tree_sitter_swift::LANGUAGE.into(),
            Lang::Toml => tree_sitter_toml_ng::LANGUAGE.into(),
            Lang::TypeScript => tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
            Lang::Tsx => tree_sitter_typescript::LANGUAGE_TSX.into(),
            Lang::Yaml => tree_sitter_yaml::LANGUAGE.into(),
            Lang::Zig => tree_sitter_zig::LANGUAGE.into(),
        }
    }

    /// Human-readable name used in verbose output.
    pub fn name(self) -> &'static str {
        match self {
            Lang::Bash => "bash",
            Lang::C => "c",
            Lang::CMake => "cmake",
            Lang::CSharp => "c#",
            Lang::Cpp => "c++",
            Lang::Css => "css",
            Lang::Dart => "dart",
            Lang::Elixir => "elixir",
            Lang::Elm => "elm",
            Lang::Erlang => "erlang",
            Lang::FSharp => "f#",
            Lang::FSharpSignature => "f# signature",
            Lang::Gleam => "gleam",
            Lang::Go => "go",
            Lang::Haskell => "haskell",
            Lang::Hcl => "hcl",
            Lang::Html => "html",
            Lang::Java => "java",
            Lang::JavaScript => "javascript",
            Lang::Julia => "julia",
            Lang::Kotlin => "kotlin",
            Lang::Lua => "lua",
            Lang::Nix => "nix",
            Lang::ObjC => "objective-c",
            Lang::OCaml => "ocaml",
            Lang::OCamlInterface => "ocaml interface",
            Lang::Php => "php",
            Lang::Python => "python",
            Lang::R => "r",
            Lang::Ruby => "ruby",
            Lang::Rust => "rust",
            Lang::Scala => "scala",
            Lang::Swift => "swift",
            Lang::Toml => "toml",
            Lang::TypeScript => "typescript",
            Lang::Tsx => "tsx",
            Lang::Yaml => "yaml",
            Lang::Zig => "zig",
        }
    }
}
